//! Assets that are not coins to copy: stablecoins, liquid-staking tokens and wrapped
//! majors. A leader swapping SOL into USDC is moving money, not entering a trade.
//!
//! GENERATED by `scripts/gen_base_assets.py` from Jupiter's verified-token list
//! (tags `stable`, `lst`, `major`) on 2026-10-02: 175 assets. Do not edit by hand;
//! rerun the script now and then to pick up new ones.

use std::collections::HashSet;
use std::sync::OnceLock;

use solana_sdk::pubkey::Pubkey;

/// True for a stablecoin, liquid-staking token or wrapped major (including wrapped SOL).
pub fn is_base_asset(mint: &Pubkey) -> bool {
    static SET: OnceLock<HashSet<Pubkey>> = OnceLock::new();
    SET.get_or_init(|| ASSETS.iter().filter_map(|(_, m)| m.parse().ok()).collect())
        .contains(mint)
}

/// (symbol, mint)
pub const ASSETS: &[(&str, &str)] = &[
    ("4dSOL", "4dFaRDBmqUJA7FzWjuoBWpDetNFfNmDyjgFjdH66JjfC"),
    ("adraSOL", "sctmY8fJucsJatwHz6P48RuWBBkdBMNmSMuBYrWFdrw"),
    ("ai20xSOL", "aiA9Ex1xGej38BP1nycxzR6TqVokoYi2xE3kqoNw2PU"),
    ("alfSOL", "aepLFer6JQBNmKwa5a87cEc2NpkyXfEQvxwTByZeGWs"),
    ("alphaSOL", "A1PHaeFxsDX6Un1g1UpWYR2MDV5vvsv2g4Mi6sNGC5cb"),
    ("anzSOL", "ANZvHuXQh5DnBMzJ55MUyMtPxkdphgBwiPeYji2B3kxS"),
    ("apySOL", "apySoLhdVa6QbvNyEjXCbET3FdUm9cCdEvYyjCU7icM"),
    ("AUSD", "AUSD1jCcCyPLybk1YnvPWsHQSrZ46dxwoMniN4N2UEB9"),
    ("AXSOL", "axso1MBZ8Hz3RdBGeyDcvc3xP5R3YNfLYqREHRvwY2t"),
    ("banxSOL", "BANXyWgPpa519e2MtQF1ecRbKYKKDMXPF1dyBxUq9NQG"),
    ("bbSOL", "Bybit2vBJGhPF52GBdNaQfUJ6ZpThSgHBobjWZpLPb4B"),
    ("BNSOL", "BNso1VUJnh4zcfpZa6986Ea66P6TCp59hvtNJ8b1X85"),
    ("bonkSOL", "BonK1YhkXEGLZzwtcvRTip3gAL9nCeQD7ppZBLXhtTs"),
    ("bpSOL", "BPSoLzmLQn47EP5aa7jmFngRL8KC3TWAeAwXwZD8ip3P"),
    ("bSOL", "bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1"),
    ("BulkSOL", "BULKoNSGzxtCqzwTvg5hFJg8fx6dqZRScyXe5LYMfxrn"),
    ("BurnSOL", "AxM7a5HNmRNHbND6h5ZMSsU8n3NLa1tskoN6m5mAgVvL"),
    ("camaoSOL", "camaK1kryp4KJ2jS1HDiZuxmK7S6dyEtr9DA7NsuAAB"),
    ("CASH", "CASHx9KJUStyftLFWGvEVf59SGeG9sh5FfcnZMVPCASH"),
    ("CDCSOL", "CDCSoLckzozyktpAp9FWT3w92KFJVEUxAU7cNu2Jn3aX"),
    ("cgntSOL", "CgnTSoL3DgY9SFHxcLj6CgCgKKoTBr6tp4CPAEWy25DE"),
    ("chimpSOL", "sctmZbtfE4dBNBEqBriQQVZLBrTaTjiTfKNRzKUcSLa"),
    ("clashSOL", "CLAShCrEjid112Mr1tWk7VqaGUAAKbiKdikDQYyDwfes"),
    ("clockSOL", "GRJQtWwdJmp5LLpy8JWjPgn5FnLyqSJGNhn5ZnCTFUwM"),
    ("CmXajSOL", "sctmoz4CV9tR91QJpWCzvazReRLLZBcyXgjjABUKxvE"),
    ("coletaSOL", "6uLQAevbHZofRWgfCsFC7tnfiRLqUG15TRxWHWxctih6"),
    ("compassSOL", "Comp4ssDzXcLeu2MnLuGNNFC4cmLPMng8qWHPvzAMU1h"),
    ("corvusSOL", "CorvuSSoLxPKLoXWXSfn8pFSMhCRHhe7Uwqe874cmwvg"),
    ("cudisSOL", "towUpSkEQr5eJWrq1nMcuJ2rbwkDxNp9mKNek4VEnBG"),
    ("DAI", "EjmyN6qEC1Tf1JxiG1ae7UTJhUxSwk1TCWNWqxWV4J6o"),
    ("dainSOL", "2LuXDpkn7ZWMqufwgUv7ZisggGkSE5FpeHCHBsRgLg3m"),
    ("daoSOL", "GEJpt3Wjmr628FqXxTgxMce1pLntcPV4uFi8ksxMyPQh"),
    ("dbcSOL", "dbcMcw2pC8EDt5eiYMiMBwe35mCWK4hRpec98bKAjML"),
    ("definSOL", "DEF1NXSZ8Th9n28hYBayrFtx9bj1EwwTiy3mhHEB9oyA"),
    ("dfdvSOL", "sctmB7GPi5L2Q5G9tUSzXvhZ4YiDMEGcRov9KfArQpx"),
    ("dicSOL", "Dicscx2kpukGBATbjgsuzdbsVRFktV19BXEHofPQwEQF"),
    ("digitalSOL", "3bfv2scCdbvumVBc3Sar5QhYXx7Ecsi8EFF2akjxe329"),
    ("digitSOL", "D1gittVxgtszzY4fMwiTfM4Hp7uL5Tdi1S9LYaepAUUm"),
    ("dlgtSOL", "DLGToUUnqy9hXxpJTm5VaiBKqnw9Zt1qzvrpwKwUmuuZ"),
    ("dSOL", "Dso1bDeDjCQxTrWHqUUi63oBvV7Mdm6WaobLbQ7gnPQ"),
    ("dualSOL", "DUAL6T9pATmQUFPYmrWq2BkkGdRxLtERySGScYmbHMER"),
    ("DUSD", "DUSDt4AeLZHWYmcXnVGYdgAzjtzU5mXUVnTMdnSzAttM"),
    ("dynoSOL", "DYNoyS3x5qgbccZg7RPXagm4xQzfnm5iwd9o8pMyJtdE"),
    ("dzSOL", "Gekfj7SL2fVpTDxJZmeC46cTYxinjB6gkAnb6EGT6mnn"),
    ("eatSOL", "EatFfcQsVg3eF4rHGWnXXcgoFT6dNu7HhkLMEfMPqa2G"),
    ("edgeSOL", "edge86g9cVz87xcpKpy3J77vbp4wYd9idEV562CCntt"),
    ("elSOL", "ELSoL1owwMWQ9foMsutweCsMKbTPVBD9pFqxQGidTaMC"),
    ("eonSOL", "eon5tgYNk5FjJUcBUcLno49t2GfpmWZDzJHeYkbh9Zo"),
    ("espresSOL", "esprDDGBNVg3pJM8EQtCsVwcUsEk5TxgYGVjD4Uu7pZ"),
    ("ETH", "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"),
    ("EURC", "HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr"),
    ("FDUSD", "9zNQRsGLjNKwCUU5Gq5LR8beUCPzQMVMqKAi3SSZh54u"),
    ("fmSOL", "fmSoLKzBY6h9b5RQ67UVs7xE3Ym6mx2ChpPxHdoaVho"),
    ("foxySOL", "FoxYewmpjh66W6PFA38k2JRYea22mxnwLLMkVmu5bNU"),
    ("fpSOL", "fpSoL8EJ7UA5yJxFKWk1MFiWi35w8CbH36G5B9d7DsV"),
    ("fuseSOL", "fuseYvhNJbSzdDByyTCrLcogsoNwAviB1WeewhbqgFc"),
    ("fwdSOL", "cPQPBN7WubB3zyQDpzTK2ormx1BMdAym9xkrYUJsctm"),
    ("genSOL", "genMsDWwH9WuuosGJyfEi4yn9rDc1boG6TNafMfFc43"),
    ("godlSOL", "gSoLFgQuJuQYgFFeYChc43yKp7j3DdjxC2JGcH7diDF"),
    ("gotmSOL", "gotMd6mpiWE4RWTv3eH3SrYjAXpxkQiZYY1zFKCNRq9"),
    ("griptoSOL", "griPkwCfWXMYfU8vBjLsPRaDWk9Bw8uYuT75E15iyy1"),
    ("gS", "gSvP9zBJ33pX7W2finzAYJZp6Q9ipNAQ19xU9PrCirz"),
    ("gtSOL", "gateMurAxe4YFoUR6J63gXGKtkbTfdkMdLjZrCmThFP"),
    ("haSOL", "haSo1Vz5aTsqEnz8nisfnEsipvbAAWpgzRDh2WhhMEh"),
    ("hausSOL", "HausGKcq9G9zM3azwNmgZyzUvYeeqR8h8663PmZpxuDj"),
    ("honestSOL", "sctmWXGT7L75psrUHV2xxyTQKndE7ZcCQRHy2z6D5ER"),
    ("hosicoSOL", "HoSipZoewmiP9cPq4Md2JNXPp6wckWUeVXZP7SFvgKi"),
    ("hSOL", "he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A"),
    ("hyloSOL", "hy1oXYgrBW6PVcJ4s6s2FKavRdwgWTXdfE69AxT7kPT"),
    ("hyloSOL+", "hy1opf2bqRDwAxoktyWAj6f3UpeHcLydzEdKjMYGs2u"),
    ("hySOL", "hySo1JDBhfEnkXuTtPRLXK9HZhkVEpYM8VoHGv9MUnN"),
    ("hyUSD", "5YMkXAYccHSGnHn9nob9xEvv6Pvka9DZWH7nTbotTu9E"),
    ("iASOL", "HALALGvdNJ8u1J3uFFSsba1tyYPRF3vnYfCQ3CpJasfD"),
    ("iceSOL", "iceSdwqztAQFuH6En49HWwMxwthKMnGzLFQcMN3Bqhj"),
    ("IndieSOL", "L33mHftsNpaj39z1omnGbGbuA5eKqSsbmr91rjTod48"),
    ("INF", "5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm"),
    ("jagSOL", "jag58eRBC1c88LaAsRPspTMvoKJPbnzw9p9fREzHqyV"),
    ("japanSOL", "JApan7h6JoKBXwSGzaNmTanfY3sBWDiirWp2gqZkMGtH"),
    ("JitoSOL", "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"),
    ("jjupSOL", "BgYgFYq4A9a2o5S1QbWkmYVFBh7LBQL8YvugdhieFg38"),
    ("joeSOL", "F41tY6PKNPtaZ6gytUBuyxkcpY4zroDr83FJsRuShKCL"),
    ("jphaseLST", "sntn1oVhhKuytG42jyjneMYnGAtzkpJsBxHNEskTfGp"),
    ("JSOL", "7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn"),
    ("jucySOL", "jucy5XJ76pHVvtPZb5TKRcGQExkwit2P5s4vY8UzmpC"),
    ("JupSOL", "jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v"),
    ("JupUSD", "JuprjznTrTSp2UFa3ZBUFgwdAmtZCq4MQCwysN55USD"),
    ("kateSOL", "7ij4w5R8dyZtzc7UDXQJefghkPPdrCKQS7t1Nj6XdDX1"),
    ("KonaSOL", "KonANtUtpQMondrv52PmdfHJbbQse91hZ7DCMaVG1eZ"),
    ("kumaSOL", "KUMAgSzADhUmwXwNiUbNHYnMBnd89u4t9obZThJ4dqg"),
    ("laineSOL", "LAinEtNLgpmCP9Rvsf5Hn8W6EhNiKLZQti1xfWMLy6X"),
    ("lanternSOL", "LnTRntk2kTfWEY6cVB8K9649pgJbt6dJLS1Ns1GZCWg"),
    ("LBTC", "LBTCgU4b3wsFKsPwBn1rRZDx5DoFutM6RPiEt1TPDsY"),
    ("legendsSOL", "LegQQkRCGrp4EqMy8NVrpMTbNi5jaQUDdhKhQSSBSE6"),
    ("lifSOL", "LSoLi4A4Pk4i8DPFYcfHziRdEbH9otvSJcSrkMVq99c"),
    ("LootSOL", "Loothu7Ac6GqtvVcUWSEZBVDAxQnyesc3fFWTGp1DZj"),
    ("lotusSOL", "gangqfNY8fA7eQY3tHyjrevxHCLnhKRrLGRwUMBR4y6"),
    ("LP-SOLAYER", "sSo1wxKKr6zW2hqf5hZrp2CawLibcwi1pMBqk5bg2G4"),
    ("LST", "LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp"),
    ("LSTache", "stacMUJ1gnBwu5tdKB1xtSmtNu9xNqvBQXoDB8eX92n"),
    ("mallowSOL", "MLLWWq9TLHK3oQznWqwPyqD7kH4LXTHSKXK4yLz7LjD"),
    ("mangoSOL", "MangmsBgFqJhW4cLUR9LxfVgMboY1xAoP8UUBiWwwuY"),
    ("memeSOL", "meme9VKXNNxquqQgvXTAauiHYP6giqrZHA2Tjzf9umy"),
    ("MonkeSOL", "MonkeD3uUj5c1w5tW8tJeTe5fX1jkpkdtD3dTibnidx"),
    ("mpSOL", "MpsoLp1YBDqeiuSrVrYH4DoAGJ3myAMmMy6crYNVSTo"),
    ("mSOL", "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"),
    ("nodzSOL", "noDZ8DqhpjcSxBnGQfX8oxeovaogZ5UCqagxWrW5LyU"),
    ("nordSOL", "nordEhq2BnR6weCyrdezNVk7TwC3Ej94znPZxdBnfLM"),
    ("nxSOL", "sctmTAsDn4tLUcemqoqYijfuRkiEfAMPi84PNq2EueR"),
    ("orcaSOL", "orcaSo6gzWvvXvAHVJQVrxWmHepCcGp7swVX1yTBuoJ"),
    ("pathSOL", "pathdXw4He1Xk3eX84pDdDZnGKEme3GivBamGCVPZ5a"),
    ("pdSOL", "aeroXvCT6tjGVNyTvZy86tFDwE4sYsKCh7FbNDcrcxF"),
    ("picoSOL", "picobAEvs6w7QEknPce34wAE4gknZA9v5tTonnmHYdX"),
    ("pineSOL", "SnKAf8aNjeYz8pY8itYn3VxFhT6Q8WNdPwy17s9USgC"),
    ("polarSOL", "PoLaRbHgtHnmeSohWQN83LkwA4xnQt91VUqL5hx5VTc"),
    ("PSOL", "pSo1f9nQXWgXibFtKf7NWYxb5enAM4qfP6UJSiXRQfL"),
    ("pumpkinSOL", "pumpkinsEq8xENVZE6QgTS93EN4r9iKvNxNALS1ooyp"),
    ("pwrSOL", "pWrSoLAhue6jUxUkbWgmEy5rD9VJzkFmvfTDV5KgNuu"),
    ("PYUSD", "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo"),
    ("RAD", "rad8NdseJYbjJUFLsv5SuBU9g29N3m4SyYndSbwoKH3"),
    ("raiSOL", "Ra1so1sTkvX3PorAM9ewqrsUMz9sPSbfFZ5oZUjN4oc"),
    ("raSOL", "HUBsveNpjo5pWqNkH57QzxjQASdTVXcSK7bVKTSZtcSX"),
    ("refiSOL", "ReFiUWiedCHUVrWGgixsASGeM8ojWN4ujc2dXTCRQoD"),
    ("riseSOL", "79bnSzQdKyqypcueaCErrMHosPgk7ZEVrLYrAXk8yk2c"),
    ("rkSOL", "EPCz5LK372vmvCkZH3HgSuGNKACJJwwxsofW6fypCPZL"),
    ("rkuSOL", "rkubjTrZYioRSeXwDnhwGQzvW3qkcin72JSxUt3WMVp"),
    ("rSOL", "RSoLp7kddnNwvvvaz4b1isQy8vcqdSwXjgm1wXaMhD8"),
    ("sctmSOL", "sctmAy9zFfZznZUWxEMgGtF6PHZ3gwoiCGcfwRua1AZ"),
    ("SOL", "So11111111111111111111111111111111111111112"),
    ("SOLANA", "11111ZSvet4hKEYUAETZWELHgkeYjyNZovzcypyAWs"),
    ("SOLb", "KTjWwdHU3PpjxX5XsbdXGr7oNzz9uig1K5uqUXsBAGS"),
    ("solSOL", "soLuqrygggsrxehAEhrsHgamSpWQUuPso3TiD8yFVwN"),
    ("soulSOL", "SouL4UuxKaFutpyZGb2weXUPEQCCsmEHSubMJEs7ttH"),
    ("sphSOL", "sphSo1j2eTLa6AB5Wjrmap8VbQoZKccCpqJ7gV5pqGM"),
    ("spikySOL", "spkyB5SzVaz2x3nNzSBuhpLSEF8otbRDbufc73fuLXg"),
    ("stakeSOL", "st8QujHLPsX3d6HG9uQg9kJ91jFxUgruwsb1hyYXSNd"),
    ("stakrSOL", "stkrHcjQGytQggswj3tCF77yriaJYYhrRxisRqe9AiZ"),
    ("stepSOL", "StPsoHokZryePePFV8N7iXvfEmgUoJ87rivABX7gaW6"),
    ("STKESOL", "stke7uu3fXHsGqKVVjKnkmj65LRPVrqr4bLG2SJg7rh"),
    ("STKSOL", "sctmqBfQtZj76PaLmepQ7Xskpu8LNMyWsXqFYAuihML"),
    ("strongSOL", "strng7mqqc1MBJJV6vMzYbEqnwVGvKKGKedeCvtktWA"),
    ("stSOL", "7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj"),
    ("superSOL", "suPer8CPwxoJPQ7zksGMwFvjBQhjAHwUMmPV4FVatBw"),
    ("thugSOL", "ThUGsoLWtoTCfb24AmQTKDVjTTUBbNrUrozupJeyPsy"),
    ("TruSOL", "6umRHtiuBd1PC6HQhfH9ioNsqY4ihZncZXNPiGu3d3rN"),
    ("uptSOL", "uPtSoL2qszk4SuPHNE2zqk1gDtqCq21ZE1yZCqvFTqq"),
    ("USD1", "USD1ttGY1N17NEEHLmELoaybftRBUSErhqYiQzvEmuB"),
    ("USDC", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
    ("USDe", "DEkqHyPN7GMRJ5cArtQFAWefqbZb33Hyf6s5iCwjEonT"),
    ("USDG", "2u1tszSeqZ3qBWF3uNGPFc8TzMk2tdiwknnRMWGWjGWH"),
    ("USDH", "USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX"),
    ("USDS", "USDSwr9ApdHk5bvJKMjzff41FfuX8bSxdKcR81vTwcA"),
    ("USDT", "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"),
    ("USDu", "9ckR7pPPvyPadACDTzLwK2ZAEeUJ3qGSnzPs8bVaHrSy"),
    ("uSOL", "uSo1ynGWS3qc2B1nN2MmEHN5cYaNbT7vJp87LtgkpV8"),
    ("USX", "6FrrzDk5mQARGc1TDYoyVnSyRdds1t4PbtohCD6p3tgG"),
    ("UXD", "7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT"),
    ("vSOL", "vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7"),
    ("WBTC", "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"),
    ("WBTC", "5XZw2LKTyrfvfiskJ78AMpackRjPcyCif1WhUsPDuVqQ"),
    ("WenSOL", "WensoLXxZJnev2YvihHFchn1dVVFnFLYvgomXWvvwRu"),
    ("wifSOL", "Fi5GayacZzUrfaCRCJtBz2vSYkGF56xjgCceZx5SbXwq"),
    ("wSOL", "sctmWrWMqZnxgYvgS1CPAoN3Pvu3JdYsihN4YWxCnaF"),
    ("wYLDS", "8fr7WGTVFszfyNWRMXj6fRjZZAnDwmXwEpCrtzmUkdih"),
    ("xandSOL", "XAnDeUmMcqFyCdef9jzpNgtZPjTj3xUMj9eXKn2reFN"),
    ("xBTC", "CtzPWv73Sn1dMGVU3ZtLv9yWSyUAanBni19YWDaznnkn"),
    ("xSHIN", "xSoL18r4U1k2ALa4yF857VDZJqCKecLtty92nscre3o"),
    ("xSOL", "B5GgNAZQDN8vPrQ15jPrXmJxVtManHLqHogj9B9i4zSs"),
    ("YIELD", "phaseZSfPxTDBpiVb96H4XFSD8xHeHxZre5HerehBJG"),
    ("yieldSOL", "yLdBrBJAYYkNMNSE48BAXYLTXhZsbHWtmWEFHgHSD6a"),
    ("yldSOL", "defiDymAmcYWJrxKsLep27XjhVNVQt6EsWXUCCgcyhq"),
    ("yontaSOL", "yontaGPyo7eLjKfAhW4eXU3L1adKbthqRHx9MsJCzvg"),
    ("zBTC", "zBTCug3er3tLyffELcvDNrKkCymbPWysGcWihESYfLg"),
    ("zenBTC", "9hX59xHHnaZXLU6quvm5uGY2iDiT3jczaReHy6A6TYKw"),
    ("zippySOL", "Zippybh3S5xYYam2nvL6hVJKz1got6ShgV4DyD1XQYF"),
    ("ZSOL", "zso1EF4k8HNteye34aD8w2Fm6pYVWMDgkgWCUrMLip1"),
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::consts::{USDC_MINT, WSOL_MINT};

    #[test]
    fn every_entry_is_a_valid_unique_address() {
        let mut seen = HashSet::new();
        for (sym, m) in ASSETS {
            let pk: Pubkey = m
                .parse()
                .unwrap_or_else(|_| panic!("{sym}: bad address {m}"));
            assert!(seen.insert(pk), "{sym}: duplicate {m}");
        }
        assert!(ASSETS.len() >= 50);
    }

    #[test]
    fn stablecoins_staked_sol_and_wrapped_sol_are_base_assets_memecoins_are_not() {
        assert!(is_base_asset(&USDC_MINT));
        assert!(is_base_asset(&WSOL_MINT));
        for sym in ["USDT", "JitoSOL", "mSOL"] {
            let (_, m) = ASSETS
                .iter()
                .find(|(s, _)| *s == sym)
                .unwrap_or_else(|| panic!("{sym} listed"));
            assert!(is_base_asset(&m.parse().unwrap()));
        }
        assert!(!is_base_asset(&Pubkey::new_unique()));
    }
}
