#!/usr/bin/env python3
"""Regenerate engine/crates/chain/src/base_assets.rs from Jupiter's verified-token list.

Base assets are tokens that are not coins to copy: stablecoins, liquid-staking
tokens and wrapped majors (Jupiter tags `stable`, `lst`, `major`). A leader who
swaps SOL into USDC is moving money, not entering a trade, so the engine ignores it.

usage: python3 scripts/gen_base_assets.py      (needs internet, no key)
"""
import datetime
import json
import re
import sys
import urllib.request

API = "https://lite-api.jup.ag/tokens/v2/tag?query="
KEEP = {"stable", "lst", "major"}
BASE58 = re.compile(r"^[1-9A-HJ-NP-Za-km-z]{32,44}$")
OUT = "engine/crates/chain/src/base_assets.rs"


def fetch(tag):
    req = urllib.request.Request(API + tag, headers={"User-Agent": "copybot-gen-base-assets"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def main() -> int:
    found = {}
    # `verified` carries the stable/major tags; `lst` is its own (smaller) listing
    for query in ("verified", "lst"):
        for t in fetch(query):
            tags = set(t.get("tags", []))
            mint = t.get("id", "")
            if tags & KEEP and BASE58.match(mint):
                found[mint] = re.sub(r"[^A-Za-z0-9._+-]", "", t.get("symbol", "")) or "?"
    if len(found) < 50:
        print(f"only {len(found)} assets came back; not overwriting {OUT}", file=sys.stderr)
        return 1
    rows = sorted(found.items(), key=lambda kv: (kv[1].lower(), kv[0]))
    today = datetime.date.today().isoformat()
    body = "".join(f'    ("{sym}", "{mint}"),\n' for mint, sym in rows)
    src = f'''//! Assets that are not coins to copy: stablecoins, liquid-staking tokens and wrapped
//! majors. A leader swapping SOL into USDC is moving money, not entering a trade.
//!
//! GENERATED by `scripts/gen_base_assets.py` from Jupiter's verified-token list
//! (tags `stable`, `lst`, `major`) on {today}: {len(rows)} assets. Do not edit by hand;
//! rerun the script now and then to pick up new ones.

use std::collections::HashSet;
use std::sync::OnceLock;

use solana_sdk::pubkey::Pubkey;

/// True for a stablecoin, liquid-staking token or wrapped major (including wrapped SOL).
pub fn is_base_asset(mint: &Pubkey) -> bool {{
    static SET: OnceLock<HashSet<Pubkey>> = OnceLock::new();
    SET.get_or_init(|| ASSETS.iter().filter_map(|(_, m)| m.parse().ok()).collect())
        .contains(mint)
}}

/// (symbol, mint)
pub const ASSETS: &[(&str, &str)] = &[
{body}];

#[cfg(test)]
mod tests {{
    use super::*;
    use crate::consts::{{USDC_MINT, WSOL_MINT}};

    #[test]
    fn every_entry_is_a_valid_unique_address() {{
        let mut seen = HashSet::new();
        for (sym, m) in ASSETS {{
            let pk: Pubkey = m.parse().unwrap_or_else(|_| panic!("{{sym}}: bad address {{m}}"));
            assert!(seen.insert(pk), "{{sym}}: duplicate {{m}}");
        }}
        assert!(ASSETS.len() >= 50);
    }}

    #[test]
    fn stablecoins_staked_sol_and_wrapped_sol_are_base_assets_memecoins_are_not() {{
        assert!(is_base_asset(&USDC_MINT));
        assert!(is_base_asset(&WSOL_MINT));
        for sym in ["USDT", "JitoSOL", "mSOL"] {{
            let (_, m) = ASSETS
                .iter()
                .find(|(s, _)| *s == sym)
                .unwrap_or_else(|| panic!("{{sym}} listed"));
            assert!(is_base_asset(&m.parse().unwrap()));
        }}
        assert!(!is_base_asset(&Pubkey::new_unique()));
    }}
}}
'''
    open(OUT, "w", encoding="utf-8").write(src)
    print(f"wrote {OUT}: {len(rows)} assets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
